name: 'react-native-bundle-size'
description: 'Github action to add React Native bundle size as status check'
author: 'Shwet Solanki'
inputs:
  token:
    description: 'Github Token'
runs: 
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'hard-drive'
  color: '#ff5000'
